### ISSUE TITLE
Is there a way to support a light theme terminal?

### ISSUE THREAD

**Issue by zw963** [Sija/debug.cr#12]
Please check following screenshot.

It awesome when debug on a black terminal theme.
![image](https://github.com/user-attachments/assets/7de2b6f6-1f10-4ce7-84a1-2fc9cec0ed5f)

But, it hard to read the value when debug on a light terminal theme.

![image](https://github.com/user-attachments/assets/b2d8d280-ba2d-4801-80b3-ece66bc7cf88)

Thanks.

**Comment by Sija** [comment]
Yes, it's possible to set custom colors through the configuration. See the related section in the README file.
