### ISSUE TITLE
version issue.

### ISSUE THREAD

**Issue by zw963** [Sija/debug.cr#13]
When i want to check the issues about debug.cr, i found the the version in the https://github.com/Sija/debug.cr/blob/master/src/debug/version.cr not same as shards.yml.

I consider use a solution like [this](https://github.com/crystal-china/procodile_cr/blob/db95ffbe6f1761c2a83e2c09732ad4317bf074fd/src/procodile.cr#L6) is better.

Thanks

**Comment by Sija** [comment]
Thanks, I've fixed it.
